### ISSUE TITLE
ActionView::Template::Error (invalid value for Integer(): "")

### ISSUE THREAD

**Issue by kristapsk** [neffets/redmine-stuff-to-do-plugin#21]
Got plug-in working, but when trying to open "Stuff To Do Page" there is error:

```
  Rendering plugins/stuff_to_do_plugin/app/views/stuff_to_do/index.html.erb within layouts/base
  Rendered plugins/stuff_to_do_plugin/app/views/stuff_to_do/_left_panes.html.erb (0.8ms)
  Rendered plugins/stuff_to_do_plugin/app/views/stuff_to_do/_panes.html.erb (1.3ms)
  Rendered plugins/stuff_to_do_plugin/app/views/stuff_to_do/index.html.erb within layouts/base (5.7ms)
Completed 500 Internal Server Error in 38ms (ActiveRecord: 20.4ms)
  
ActionView::Template::Error (invalid value for Integer(): ""):
     6:     </h3>
     7: 
     8:     <ol id="doing-now">
     9:       <% unless stuff_for(@doing_now).empty? %>
    10:       <%= render partial: 'item', collection: stuff_for(@doing_now) %>
    11:       <% else %>
    12:       <li class="empty-list">
  
plugins/stuff_to_do_plugin/app/helpers/stuff_to_do_helper.rb:50:in `collect'
plugins/stuff_to_do_plugin/app/helpers/stuff_to_do_helper.rb:50:in `stuff_for'
plugins/stuff_to_do_plugin/app/views/stuff_to_do/_left_panes.html.erb:9:in `_plugins_stuff_to_do_plugin_app_views_stuff_to_do__left_panes_html_erb___3363736011916610523_81280'
plugins/stuff_to_do_plugin/app/views/stuff_to_do/_panes.html.erb:5:in `block in _plugins_stuff_to_do_plugin_app_views_stuff_to_do__panes_html_erb__2214620366020765069_81260'
plugins/stuff_to_do_plugin/app/views/stuff_to_do/_panes.html.erb:2:in `_plugins_stuff_to_do_plugin_app_views_stuff_to_do__panes_html_erb__2214620366020765069_81260'
plugins/stuff_to_do_plugin/app/views/stuff_to_do/index.html.erb:33:in `_plugins_stuff_to_do_plugin_app_views_stuff_to_do_index_html_erb__2613558879514821695_81240'
plugins/stuff_to_do_plugin/app/controllers/stuff_to_do_controller.rb:22:in `block (2 levels) in index'
plugins/stuff_to_do_plugin/app/controllers/stuff_to_do_controller.rb:21:in `index'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Any hints where could be a problem and how to solve it?

```
Environment:
  Redmine version                4.0.6.stable
  Ruby version                   2.7.0-p0 (2019-12-25) [x86_64-linux-gnu]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.25.1
  Filesystem                     
Redmine plugins:
  redmine_dark                   1.0.2
  stuff_to_do_plugin             0.8.0
```

**Comment by neffets** [comment]
Thank you for the Bug Report.

Issue: it's missing a value for "doing_now"

1) workaround

Go to Admin Settings Plugin Stuff Todo Page and set a value.

2) bug
In next release we will set a default value for "doing_now"

**Comment by kristapsk** [comment]
> Issue: it's missing a value for "doing_now"
> 
> 1. workaround
> 
> Go to Admin Settings Plugin Stuff Todo Page and set a value.

Can't figure out where can I set such value...

![image](https://github.com/neffets/redmine-stuff-to-do-plugin/assets/4500994/4fd0f110-2df4-4d7d-862a-d42eb7c8d2d0)

**Comment by kristapsk** [comment]
Ok, figured out, it's "stuff todo count limit". Thanks!
